name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build the package
        run: npm run build
      #      - name: Vitest tests
      #        run: npm run test:unit -- --run
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Playwright tests
        run: npm run test
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: test-results
          retention-days: 7
